### ISSUE TITLE
Dedup languages

### ISSUE THREAD

**Issue by AndreySurzhan** [AndreySurzhan/ChecklistSLApi#50]

**Comment by Gromoff9999** [comment]
**As a QA I would like it to be impossible to add a duplicate  language via the API, since this leads to:**
1) Duplicate languages are saved in BD;
2) When creating a checklist via the UI, a 500 error is issued
3) When creating an item via the UI, the translation is duplicated

**AC:**
-Add validation for duplicate languages ​​on Post registration and Patch user methods;
-When duplicating a language using the Post registration and Patch user methods via the API, a response status of 400 should be returned, as well as a duplicate language should not be stored in the database;

**or**
-Add clipping from the body of duplicate languages ​​when using Post registration and Patch user methods. This option will be more user friendly.
